//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ticket
    {
        public int ticket_id { get; set; }
        [DisplayName("Ticket Name")]
        public string ticket_name { get; set; }
        [DisplayName("Ticket Description")]
        public string ticket_desc { get; set; }
        [DisplayName("Ticket Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ticket_created_date { get; set; }
        [DisplayName("Ticket Assignee")]
        public string ticket_assignee { get; set; }
        [DisplayName("Ticket Owner")]
        public string ticket_owner { get; set; }
        [DisplayName("Ticket Category")]
        public string ticket_category { get; set; }
        [DisplayName("Ticket Status")]
        public string ticket_status { get; set; }
    }
}
