//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public int UserID { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage ="Kolom email harus diisi")]
        public string UserName { get; set; }
        [MinLength(3)]
        [RegularExpression("((?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%]).{6,20})")]
        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Kolom Password harus diisi")]
        public string Password { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string RoleName { get; set; }
    }
}
